### ISSUE TITLE
s2i-php-container sample

### ISSUE THREAD

**Issue by littlezo** [kubesphere/s2ioperator#136]
希望官网出一个 s2i-php-container  的样品
产考`https://github.com/sclorg/s2i-php-container` 写了 `https://github.com/littlezo/s2i-php-container` 最终能构建成功，但运行是项目代码没了导致无法正常启动
希望官网能出一个demo供产考   需求  swoole  无 web服务器  不需要nginx 这类似但web服务器  纯php环境就好

**Comment by soulseen** [comment]
https://github.com/sclorg/s2i-php-container 这里有一个 s2i php image 可以参考

**Comment by littlezo** [comment]
> /分配@shaowenchen

是有希望了吗  要出单php-cli 的镜像构建demo 吗

**Comment by littlezo** [comment]
> /assign @shaowenchen
我通过我的方式实现了一个版本  https://github.com/littlezo/k8s-php-s2i.git     但效果可能不是很好，希望看一下这么优化能更好的融入  kubesphere

**Comment by littlezo** [comment]
> /assign @shaowenchen

https://github.com/littlezo/k8s-php-s2i/blob/master/s2i-builder/s2i/bin/run  启动脚本思路
