### ISSUE TITLE
Image builder additional code languages

### ISSUE THREAD

**Issue by Born2Bake** [kubesphere/s2ioperator#139]
Hi,

I am wondering, is there any plans for additional code languages in image builder? I can see it currently supports java/nodejs/python in Kubesphere v3.0. If I want to add .net core (https://github.com/redhat-developer/s2i-dotnetcore), is it supported?

Thank you

**Comment by shaowenchen** [comment]
duplicate  https://github.com/kubesphere/s2ioperator/issues/138
