### ISSUE TITLE
✨Webhook support

### ISSUE THREAD

**Issue by magicsong** [kubesphere/s2ioperator#6]
Trigger a s2irun when recieves webhooks from github or gitlab

**Comment by JohnNiang** [comment]
Hi @LinuxSuRen , in fact, both the triggers with GET and POST method are working well, but you might miss the header, `Content-Type`.

We could use following command to trigger S2iBuilder with POST method:

```bash
curl -X POST -H "Content-Type: application/json" s2ioperator-trigger-service.kubesphere-devops-system:8081/s2itrigger/v1alpha1/general/namespaces/my-project/s2ibuilders/johnniang-halo-s2i-latest-ahs

# Or
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" s2ioperator-trigger-service.kubesphere-devops-system:8081/s2itrigger/v1alpha1/general/namespaces/my-project/s2ibuilders/johnniang-halo-s2i-latest-ahs
```

**Comment by JohnNiang** [comment]
I think this issue has been fixed by:
- https://github.com/kubesphere/s2ioperator/pull/132

/close
